development:
  host: 'http://localhost:9200'
  transport_options:
    request:
      timeout: 10

test:
  host: 'http://localhost:9200'
  transport_options:
    request:
      timeout: 10

production:
  host: 'http://localhost:9200'
  transport_options:
    request:
      timeout: 10