version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=tuniversidad_development
      - POSTGRES_PASSWORD=tuniversidad
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: elasticsearch
    environment:
      - cluster.name=psupro-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  api:
    build: ./api/tuniversidad
    command: bin/rails server --port 3000 --binding 0.0.0.0

    volumes:
      - .:/app
    expose:
      - "3000"
    depends_on:
      - db
      - elasticsearch
    links:
     - elasticsearch
    ports:
      - "3000:3000"

volumes:
  esdata1:
    driver: local


  # front:
  #   container_name: front
  #   build:
  #     context: ./front
  #   volumes:
  #     - '.:/usr/src/app'
  #     - '/usr/src/app/node_modules'
  #   ports:
  #     - '5000:5000'
  #   environment:
  #     - NODE_ENV=development
  #   links:
  #     - api
      
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-nginx
  #   links:
  #     - api
  #   ports:
  #     - "80:80"