version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=tuniversidad_development
      - POSTGRES_PASSWORD=123456

  api:
    build: ./api/tuniversidad
    volumes:
      - .:/app
    expose:
      - "3000"
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    links:
      - api
    ports:
      - "80:80"